name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  DIA_DA_SEMANA: quinta
  agent: ubuntu-latest
jobs:
  get_variables:
    runs-on: ubuntu-latest
    steps:
      - name: "get variables"
        run: |
          echo "$hoje é $DIA_DA_SEMANA - SO: $agent"
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: list_dir
      run: |
        ls -lah
        